initrdscripts-secure-core: remove /sys and /proc from package
Issue: LIN1018-2733

The following failure is shown during secure-core-image-initramfs:do_rootfs():

Error: Transaction check error:
  file /proc conflicts between attempted installs of initrdscripts-secure-core-1.0-r0.corei7_64 and base-files-3.0.14-r89.intel_x86_64
  file /sys conflicts between attempted installs of initrdscripts-secure-core-1.0-r0.corei7_64 and base-files-3.0.14-r89.intel_x86_64

So remove /sys and /proc as base-files has already provided them.

(master rev: bd155539ec1677148ff516249e33890953fe763b) -- backport

Signed-off-by: Yunguo Wei <yunguo.wei@windriver.com>