Revert "grub-efi: suppress x86 builds"
This reverts commit 2e51cc2e64188c3d00e443dd3f2a8565fe5a84de.

It caused errors like:
ERROR: Nothing RPROVIDES 'lib32-grub-efi'
lib32-grub-efi was skipped: incompatible with host i686-wrsmllib32-linux (not in COMPATIBLE_HOST)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>