rpm-native: disable audit plugin
Issue: LIN1021-1501

* enable this plugin will cause undeterministic build. whether to build
audit plugin depends on whether libaudit exists on the host.

* on centos7, rpm-native will compile failed with following error:
../../git/plugins/audit.c:3:10: fatal error: libaudit.h: No such file or directory
The failed reason is gcc in buildtools can find host libaudit, but
cannot find libaudit.h. This is a workaround to fix this.

(LOCAL REV: NOT UPSTREAM) -- sent to meta-secure-core on 20211022

Signed-off-by: Changqing Li <changqing.li@windriver.com>